version: "3.2"
services:
    haproxy:
        image: dockercloud/haproxy:latest
        restart: unless-stopped
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        environment:
            MODE: tcp
        expose:
            - 5671
            - 5672
            - 8000
            - 8080
        links:
            - cbemq
            - cbeapp
        ports:
            - "5671:5671"
            - "5672:5672"
            - "8000:8000"
            - "8080:8080"
            
    cbeapp:
        image: semprini/cbe-utilities
        restart: unless-stopped
        environment:
            - DBENGINE=postgresql
            - DBHOST=cbedb
            - DBNAME=cbe
            - DBPASSWORD=super
            - DBUSER=super
            - MQHOST=cbemq
            - MQUSER=super
            - MQPASSWORD=super
            - MQRESTSERVER=cbe.sphinx.co.nz
            - MQRESTPORT=443
            - MQRESTPROTOCOL=https
            - SUNAME=super
            - SUEMAIL=super@super.com
            - SUPASS=super
        depends_on:
            - cbedb
            - cbemq
        ports:
            - 8000
            
    cbedb:
        image: postgres:latest
        restart: unless-stopped
        volumes:
            - "db-data:/var/lib/postgresql/data"
        environment:
            POSTGRES_PASSWORD: super
            POSTGRES_USER: super
            POSTGRES_DB: cbe
            
    cbemq:
        image: rabbitmq:3-management-alpine
        restart: unless-stopped
        environment:
            RABBITMQ_DEFAULT_USER: super
            RABBITMQ_DEFAULT_PASS: super
            TCP_PORTS: "5672,5671"
        ports:
            - "8080:15672"
            - "5671"
            - "5672"

    cbedbadmin:
        image: dpage/pgadmin4
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: super@super.com
            PGADMIN_DEFAULT_PASSWORD: super
        ports:
            - "80:80"
        links:
            - cbedb
volumes:
    db-data:

